# CDX — NXP ASK data-plane acceleration module
include $(srctree)/drivers/net/ethernet/freescale/sdk_fman/ncsw_config.mk

FMAN_DRIVER_PATH = $(srctree)/drivers/net/ethernet/freescale/sdk_fman
ccflags-y += -I$(FMAN_DRIVER_PATH)/src/wrapper
ccflags-y += -I$(srctree)/drivers/crypto/caam
ccflags-y += -DSEC_PROFILE_SUPPORT -DVLAN_FILTER -DWIFI_ENABLE -DENABLE_EGRESS_QOS
ccflags-y += -DDPA_IPSEC_OFFLOAD
ccflags-y += -Werror -I$(src) -DENDIAN_LITTLE -DGCC_TOOLCHAIN

obj-$(CONFIG_ASK_CDX) += cdx.o

cdx-y += cdx_main.o cdx_hal.o cdx_timer.o cdx_cmdhandler.o layer2.o \
	control_tx.o control_rx.o control_ipv4.o control_ipv6.o \
	control_vlan.o control_pppoe.o control_socket.o control_bridge.o \
	control_stat.o control_ipsec.o query_Rx.o control_tunnel.o \
	control_qm.o control_wifi.o \
	devman.o cdx_debug.o dpa_cfg.o cdx_dev.o \
	cdx_dpa.o cdx_ehash.o devoh.o cdx_ceetm_app.o \
	dpa_control_mc.o cdx_mc_query.o dpa_ipsec.o cdx_dpa_ipsec.o \
	query_ipsec.o cdx_ifstats.o control_rtp_relay.o cdx_reassm.o \
	dpa_wifi.o voip.o cdx_qos.o vsp_cfg.o procfs.o \
	cdx_cmd_validator.o
